controllers:
  resource: ../../src/Controller/
  type: annotation

controllers_front:
  resource: ../../src/Controller/Front
  type: annotation
  name_prefix: front_

controllers_security:
  resource: ../../src/Controller/Security
  type: annotation
  name_prefix: security_

kernel:
  resource: ../../src/Kernel.php
  type: annotation
