controllers:
  resource: ../../src/Controller/
  type: annotation

controllers_front:
  resource: ../../src/Controller/Front
  type: annotation
  name_prefix: front_

kernel:
  resource: ../../src/Kernel.php
  type: annotation
